# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  resourceGroup: 'microservices'
  containerName: 'hello-world-17'
  imageName: 'devs4j/hello-world-17'
  dnsName: 'hello-world-17'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$pomXml = Get-Content .\pom.xml
      $version=$pomXml.project.version
      Write-Host "##vso[task.setvariable variable=version]$version"

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      [xml]$pomXml = Get-Content .\pom.xml
      $version=$pomXml.project.version
      Write-Host "##vso[task.setvariable variable=version]$version"


- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: 



- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: $(imageName)
    tags: |
      $(version)



- task: AzureCLI@1
  inputs:
    connectedServiceNameARM: ''
    scriptLocation: 'inlineScript'
    inlineScript: |
      az container delete --resource-group $(resourceGroup) --name $(containerName) --yes
      az container create --resource-group $(resourceGroup) --name $(containerName) --image $(imageName):$(version) --dns-name-label $(dnsName) --ports 8083
      az container show --resource-group $(resourceGroup) --name $(containerName) --query "{FQDN:ipAddress.fqdn,ProvisioningState:provisioningState}" --out table
